AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: .NET Lambda Demo

Globals:
  Function:
    Timeout: 20

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/HelloWorldFunction
      Handler: HelloWorld.Function::FunctionHandler
      Runtime: dotnet6
      MemorySize: 512
      Layers:
        - arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14
      Policies:
        - CloudWatchLambdaInsightsExecutionRolePolicy
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  MyDotNetFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for MyDotNetFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MyDotNetFunctionArn:
    Description: "MyDotNetFunction Lambda Function ARN"
    Value: !GetAtt MyDotNetFunction.Arn
  MyDotNetFunctionIamRole:
    Description: "Implicit IAM Role created for MyDotNetFunction"
    Value: !GetAtt MyDotNetFunctionRole.Arn
  
  
  